In [60]:
import torch
import numpy as np
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

torch over numpy to run on gpu-s for faster processing

we will use nn.linear class to initialize weights and biases of a linear model

use tensordataset to split the data into smaller chunks to run code, returns a tuple with 2 elements, in our cse inputs and targets

use dataloader to split data into bathces of predefined size; enbles shuffling and ramdom sampling of data

In [61]:
print(torch.__version__)

2.1.2


In [62]:
t1=torch.tensor(4.0)
t1

tensor(4.)

In [63]:
t1.dtype

torch.float32

In [64]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [65]:
t2.dtype

torch.float32

In [66]:
t3=torch.tensor([[5.,6],
                 [7,8],
                 [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [67]:
t4=torch.tensor([
    [[11,12,13],
     [13,14,15]],
     [[15,16,17],
      [17,18,19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [68]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [69]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [70]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [71]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

In [72]:
# bnasic tensor operations
x=torch.tensor(3.0)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [73]:
x.is_leaf

True

In [74]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [75]:
# y.retain_grad()
y.backward()
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)
print('dy/dw 2:',w.grad_fn)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)
dy/dw 2: None


In [76]:
w2=torch.tensor(42.,requires_grad=True)
b2=torch.tensor(52.,requires_grad=True)
y2=w2+b2

In [77]:
y2.backward
print(w2.grad)

None


In [78]:
t6=torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [79]:
t7=torch.concatenate((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [80]:
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [81]:
t9=t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [82]:
x=np.array([[1,2],
            [3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [83]:
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [84]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [85]:
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

Fundamentals of Pytorch and Numpy done.
Next progress towards linear regression znd gradient descent

Video course Timestamp 25.28 / 1.43.32  

In [86]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [87]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [88]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [89]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.4632, -1.0548, -0.7585],
        [ 0.3214,  0.5113,  0.3676]], requires_grad=True)
tensor([ 0.7205, -0.0881], requires_grad=True)


In [90]:
inputs @ w.t()+b

tensor([[-136.3847,   73.4404],
        [-182.8027,   97.6835],
        [-224.9202,  117.7132],
        [-119.9524,   68.2832],
        [-185.6007,   96.9092]], grad_fn=<AddBackward0>)

In [91]:
def model(x):
    return x @ w.t()+b

In [92]:
preds=model(inputs)
print(preds)

tensor([[-136.3847,   73.4404],
        [-182.8027,   97.6835],
        [-224.9202,  117.7132],
        [-119.9524,   68.2832],
        [-185.6007,   96.9092]], grad_fn=<AddBackward0>)


In [93]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [94]:
diff=preds-targets
torch.sum(diff * diff)/diff.numel()

tensor(33004.8867, grad_fn=<DivBackward0>)

to get rid of negatives in diff, square numbers; * does a element wise multiplication

In [95]:
# mean squared error loss 
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [96]:
loss=mse(preds,targets)
print(loss)

tensor(33004.8867, grad_fn=<DivBackward0>)


In [97]:
loss.backward()

In [98]:
print(w)
print(w.grad)

tensor([[-0.4632, -1.0548, -0.7585],
        [ 0.3214,  0.5113,  0.3676]], requires_grad=True)
tensor([[-20472.7559, -23199.8672, -14111.5156],
        [    57.2028,   -577.0646,   -267.9670]])


In [99]:
print(b)
print(b.grad)

tensor([ 0.7205, -0.0881], requires_grad=True)
tensor([-246.1321,   -1.1941])


In [100]:
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5

In [101]:
w,b

(tensor([[-0.2585, -0.8228, -0.6174],
         [ 0.3208,  0.5171,  0.3703]], requires_grad=True),
 tensor([ 0.7229, -0.0881], requires_grad=True))

In [102]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(22470.4414, grad_fn=<DivBackward0>)


the grad values for w and b should be reset to zero, else the next operation will add to existing grad values

In [103]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


to train the model repeat the above operation x number of times, called epochs

In [104]:
for i in range(100):
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [105]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(219.3056, grad_fn=<DivBackward0>)


In [106]:
preds

tensor([[ 63.1799,  73.5702],
        [ 82.5140,  99.6336],
        [108.3273, 130.0730],
        [ 54.9510,  55.7300],
        [ 82.8338, 106.3957]], grad_fn=<AddBackward0>)

In [107]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

xxxxxxxxx
Starting work on using Troch for gradient descent

In [108]:
# inputs are temperature, rainfall, humidity
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70],
                 [74,66,43],
                 [91,87,65],
                 [88,114,59],
                 [101,44,37],
                 [68,96,71],
                 [73,66,44],
                 [92,87,64],
                 [87,135,57],
                 [103,43,36],
                 [68,97,70]],
                 dtype='float')

# targets are apples, oranges
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119],
                  [57,69],
                  [80,102],
                  [118,132],
                  [21,38],
                  [104,119],
                  [57,69],
                  [82,100],
                  [118,134],
                  [20,38],
                  [102,120]],
                  dtype='float')

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [109]:
inputs.shape

torch.Size([15, 3])

In [110]:
targets.shape

torch.Size([15, 2])

use tensordataset to split the data into smaller chunks to run code, returns a tuple with 2 elements, in our cse inputs and targets

In [111]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]], dtype=torch.float64),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]], dtype=torch.float64))

use dataloader to split data into bathces of predefined size; enbles shuffling and ramdom sampling of data

In [112]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [113]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[101.,  44.,  37.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 88., 114.,  59.]], dtype=torch.float64)
tensor([[ 21.,  38.],
        [ 81., 101.],
        [ 56.,  70.],
        [103., 119.],
        [118., 132.]], dtype=torch.float64)


we will use nn.linear class to initialize weights and biases of a linear model

In [121]:
# defining model usin nn.linear
model=nn.Linear(3,2,dtype=float)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2480,  0.4304,  0.0774],
        [-0.3894,  0.2722,  0.1729]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.2886, -0.4884], dtype=torch.float64, requires_grad=True)


In [122]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2480,  0.4304,  0.0774],
         [-0.3894,  0.2722,  0.1729]], dtype=torch.float64, requires_grad=True),
 Parameter containing:
 tensor([-0.2886, -0.4884], dtype=torch.float64, requires_grad=True)]

In [124]:
# generate predictions using the nn.linear model above
# inputs
preds=model(inputs)
preds

tensor([[ 49.9840,  -3.2412],
        [ 65.1131,  -0.9029],
        [ 83.4554,  12.1395],
        [ 46.3819, -22.1045],
        [ 63.5647,  10.8791],
        [ 49.8016,  -3.9028],
        [ 64.7601,  -1.0022],
        [ 75.1726,   6.4786],
        [ 46.5643, -21.4429],
        [ 63.3941,  11.4414],
        [ 49.6310,  -3.3405],
        [ 64.9307,  -1.5645],
        [ 83.8084,  12.2389],
        [ 46.5525, -22.6668],
        [ 63.7471,  11.5407]], dtype=torch.float64, grad_fn=<AddmmBackward0>)