In [2]:
import torch
import numpy as np


In [3]:
print(torch.__version__)

2.1.2


In [4]:
t1=torch.tensor(4.0)
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

In [6]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [7]:
t2.dtype

torch.float32

In [8]:
t3=torch.tensor([[5.,6],
                 [7,8],
                 [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [9]:
t4=torch.tensor([
    [[11,12,13],
     [13,14,15]],
     [[15,16,17],
      [17,18,19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [10]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [11]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [12]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [13]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

In [14]:
# bnasic tensor operations
x=torch.tensor(3.0)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [15]:
x.is_leaf

True

In [16]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [17]:
# y.retain_grad()
y.backward()
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)
print('dy/dw 2:',w.grad_fn)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)
dy/dw 2: None


In [18]:
w2=torch.tensor(42.,requires_grad=True)
b2=torch.tensor(52.,requires_grad=True)
y2=w2+b2

In [19]:
y2.backward
print(w2.grad)

None


In [20]:
t6=torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [21]:
t7=torch.concatenate((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [22]:
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [23]:
t9=t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [24]:
x=np.array([[1,2],
            [3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [25]:
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [26]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [27]:
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

Fundamentals of Pytorch and Numpy done.
Next progress towards linear regression znd gradient descent

Timestamp 25.28 / 1.43.32  

In [28]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [29]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [30]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [31]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.5658,  0.5662,  0.7423],
        [-0.2970, -1.5794,  0.5701]], requires_grad=True)
tensor([ 1.9479, -0.7448], requires_grad=True)


In [32]:
inputs @ w.t()+b

tensor([[ 113.1026, -103.7318],
        [ 150.7646, -130.2738],
        [ 170.0907, -205.1595],
        [ 111.4691,  -77.8581],
        [ 147.3001, -132.9556]], grad_fn=<AddBackward0>)

In [33]:
def model(x):
    return x @ w.t()+b

In [34]:
preds=model(inputs)
print(preds)

tensor([[ 113.1026, -103.7318],
        [ 150.7646, -130.2738],
        [ 170.0907, -205.1595],
        [ 111.4691,  -77.8581],
        [ 147.3001, -132.9556]], grad_fn=<AddBackward0>)


In [35]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [36]:
diff=preds-targets
torch.sum(diff * diff)/diff.numel()

tensor(29540.1445, grad_fn=<DivBackward0>)

to get rid of negatives in diff, square numbers; * does a element wise multiplication

In [39]:
# mean squared error loss 
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [40]:
loss=mse(preds,targets)
print(loss)

tensor(29540.1445, grad_fn=<DivBackward0>)
